version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget_buddy
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: budget_buddy_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
