services:
  app:
    container_name: budget_buddy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - path: ./.env
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app_network

volumes:
  postgres-data:
  redis-data:

networks:
  app_network:
    driver: bridge
